# Generated by Django 5.1.6 on 2025-03-17 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_adminlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminlog",
            name="task_id",
        ),
        migrations.AddField(
            model_name="adminlog",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.task",
            ),
        ),
    ]
