# Generated by Django 5.1.6 on 2025-03-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_remove_adminlog_task_id_adminlog_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminlog",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.task",
            ),
        ),
    ]
